### ISSUE TITLE
Form Tools 3 reCAPTCHA Form_builder form: Fatal Error when not "logged-in"

### ISSUE THREAD

**Issue by johnbleck3** [formtools/api#10]
Fatal error: Call to a member function prepare() on a non-object in /var/www/forms.buffalonews.com/global/code/Database.class.php on line 65

When not logged in reCAPTCHA can not load.

**Comment by johnbleck3** [comment]
I forgot to mention - initially the "include" in modules/form_builder/smarty_plugins/function.captcha.php
 include_once(realpath(__FILE__ . "/../../../global/api/api.php"));
I had to change to:
 include_once(realpath(__DIR__ . "/../../../global/api/api.php"));
The stream failed as __FILE__ - was referencing "modules/form_builder/published"

**Comment by benkeen** [comment]
Ah yes! I actually just released the update to the API so this will break. I'll see if I can patch it up tonight.

**Comment by benkeen** [comment]
This'll be patched on the Form Builder module:
https://github.com/formtools/module-form_builder/issues/8

**Comment by johnbleck3** [comment]
I keep throwin the bugs - and you just keep knockin em out! fixed with latest module and lovin it.

**Comment by benkeen** [comment]
haha thanks :)
